### ISSUE TITLE
build error:Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ustczzh** [jibuntu/keymap#1]
cargo 1.35.0
pop os 19.04

here is build output:
# cargo build
    Updating crates.io index
Segmentation fault (core dumped)

how can I solve this?

**Comment by jibuntu** [comment]
**Thank you for reporting the issue.**

This program is using the [bindgen](https://crates.io/crates/bindgen) of the Rust library.
Bindgen required some llvm toolchain.
Please look the requirements of bindegn.
[https://rust-lang.github.io/rust-bindgen/requirements.html#clang](https://rust-lang.github.io/rust-bindgen/requirements.html#clang)

**Comment by jibuntu** [comment]
**Thank you for reporting issue.**
I cannot solve this issue.
I am sorry.
